### ISSUE TITLE
command 'git-blame.statusClick' not found

### ISSUE THREAD

**Issue by hrdwdmrbl** [solomonkinard/public#1]
![Screenshot 2023-03-16 at 15 50 10](https://user-images.githubusercontent.com/554881/225736784-60f4c25a-3479-46da-b644-14a9548e1be6.png)

**Comment by solomonkinard** [comment]
More information, such as the version number, your operating system, and how to reproduce it?

**Comment by hrdwdmrbl** [comment]
Steps:

1. Open command pallet
2. Search for "Git blame"
3. Hit enter

I think you should put all of these commands in the pallet because keyboard shortcuts rock!
![Screenshot 2023-03-17 at 00 47 20](https://user-images.githubusercontent.com/554881/225815064-1e078bca-0582-4dd8-b27c-c2a725d137a9.png)

**Comment by solomonkinard** [comment]
Fixed  The second point is a good idea that probably deserves its own new issue, in case you'd like to open it along with any other new feature requests.

**Comment by hrdwdmrbl** [comment]
@solomonkinard Thanks! BTW, I really appreciate your extension. I used to use the other popular ones but they were SO SLOW! Having a very simple extension that just does Git Blame and does it fast is very nice.
