### ISSUE TITLE
Way to clear all bookmark?

### ISSUE THREAD

**Issue by quyle92** [solomonkinard/public#10]
Hi there,
First I'd like to thank you for creating great plugin for VSC community.
I have just installed your plugin but it seems it does not have function to remove all bookmarks at once.
Can you please take a look again?
Thank you,
Q.

**Comment by solomonkinard** [comment]
When I use the button in the following photo, removing all at once seems to work for me. What button are you using? What operating system?

<img width="285" alt="Screenshot 2023-11-23 at 11 15 48 AM 2" src="https://github.com/solomonkinard/public/assets/297660/012d6d7e-9c3c-4e94-a5aa-d050764896e6">

**Comment by quyle92** [comment]
OK... cool! I did not notice there is such button.
Thanks much.
