### ISSUE TITLE
can't work with vscode 1.17.0

### ISSUE THREAD

**Issue by aiyartoth** [solomonkinard/public#11]
![image](https://github.com/solomonkinard/public/assets/13058758/58a04da8-8efd-4736-84bc-f98b4b000440)

**Comment by solomonkinard** [comment]
It looks like engine is set to 1.75.0 in https://vsixlens.com/?id=solomonkinard.chrome-extension-api&version=0.0.2. Should this be changed to 1.70.0 or would you like to upgrade?

**Comment by solomonkinard** [comment]
This was just fixed in version 0.0.3. Thanks.
