### ISSUE TITLE
How is the `logClickUrls` supposed to work?

### ISSUE THREAD

**Issue by robin-pham** [solomonkinard/public#13]
I've tried arbitrary regex's as keys with capture groups and I'm not sure if I'm doing something wrong or if there's some documentation I'm missing. 

I was under the impression that this feature would turn parts of the 1 liner git blame message into clickable urls but perhaps I'm wrong.

e.g. config
```
  "git-blame.config.logClickUrls": {
    "\\(#(\\d+)\\)": "https://github.com/test/repo/pull/$1"
  },
```

<img width="989" alt="Screenshot 2024-05-06 at 5 12 08 PM" src="https://github.com/solomonkinard/public/assets/5697723/61cab843-a0ba-4d9b-93a7-d45573c4233e">

I figured that `#12345` would now be clickable.

**Comment by solomonkinard** [comment]
It looks like you're right. I probably made a mistake. The good news is that I was able to get your configuration to work without a code change. I'll put a code change on the long list of things to eventually get to, now that you have a functional workaround.

```  "git-blame.config.logClickUrls": {
    "(#(\\d+))": "https://github.com/test/repo/pull/$1"
  }```

**Comment by robin-pham** [comment]
hmm I think maybe I'm missing something still, even with that new regex, nothing seems clickable. Am I supposed to command click? Is there a hotkey?

**Comment by solomonkinard** [comment]
Command click seems to work.

**Comment by solomonkinard** [comment]
This seemed to work just fine with a regular click.
<img width="450" alt="Screenshot 2024-05-07 at 20 49 14" src="https://github.com/solomonkinard/public/assets/297660/dd56a7f6-5392-41b6-847f-66353818efc0">

**Comment by robin-pham** [comment]
Oooh ok I understand the feature now. I was expecting the inline comments to be clickable e.g. 

<img width="386" alt="Screenshot 2024-05-08 at 11 40 38 AM" src="https://github.com/solomonkinard/public/assets/5697723/5474eb70-4c9a-47ea-a452-78da3a9a2bfc">

I can contribute to this if the code is available anywhere for me to hack on, I feel like inline clicks are much more valuable and similar to the other git blame plugins out there

**Comment by solomonkinard** [comment]
Your completely new feature request has been implemented [here](https://whowideweb.com/?s=2024/05/git-blame%20clickable%20hover), in an experimental build. Enjoy.
