### ISSUE TITLE
Inquiry about Git Web URL

### ISSUE THREAD

**Issue by nikkizhu1999** [solomonkinard/public#15]
![20240624-114850](https://github.com/solomonkinard/public/assets/173651187/95722f56-4fdf-411a-992e-fcecb77d5eef)

Hi there, i want to replace the "doc" (which is the name of a project in GitLab) with parameters like "$ID". Do we have this? I would assume it is "$githubproject" or something, but it doesn't work

Looking forward to your reply, thanks! :)))

**Comment by solomonkinard** [comment]
If the online web url started from "https://example.com/doc/commit/", you'd be able to open the commit on the web by adding "$ID" at the end. But in your case you want to replace doc with a project. So the result would be "https://example.com/project/commit/$ID". It could be saved as a workspace only setting, like what's shown in the photo. Does that work, is this a bug, or a new feature request?
 
<img width="436" alt="Screenshot 2024-06-24 at 00 12 08" src="https://github.com/solomonkinard/public/assets/297660/53d068a2-edba-4bc9-8395-60b15251c2b1">

**Comment by nikkizhu1999** [comment]
Hi solomonkinard,

Yes, it works. However, what should I do if I have more than one project, such as doc, doc2, and doc3? Currently, I have to manually change the settings from "https://example.com/doc/commit/" to "https://example.com/doc2/commit/" when the file belongs to doc2. Is there a parameter or method I can use to automatically fill in the appropriate project URL based on the file's project?

**Comment by solomonkinard** [comment]
Your [new feature request](https://docs.google.com/document/d/18owmZ6J_GX4DMJVW_WmMFgHSOecG0tzAQGO0BdfzB3U) has been rolled into 0.2.22 for you to enjoy. Hopefully it solves your problem. Just add a ".gitblame" file anywhere you want - to replace variables. Here the format.

```
{
  "openOnline": {
    "url": "https://example.com/$PROJECT/$ID",
    "replacements": {
      "$PROJECT": "doc1",
      "wHaTeVeR u WaNt": "tO rEpLaCe",,
      ...
    }
  }
}
```

**Comment by phtty** [comment]
This configuration file doesn't seem to support vscode variables, such as ${workspaceFolderBasename}, and hopefully this feature will be added to the settings to simplify some of the configuration work

**Comment by solomonkinard** [comment]
v0.2.57 now supports `${workspaceFolderBasename}`. If others are requested, please comment on an open (or make a new) bug, stating exactly which ones are desired. If all 19 are wanted, please share why.

**Comment by nikkizhu1999** [comment]
> v0.2.57 now supports `${workspaceFolderBasename}`. If others are requested, please comment on an open (or make a new) bug, stating exactly which ones are desired. If all 19 are wanted, please share why.

Thank you!
