### ISSUE TITLE
Invalid .gni file association

### ISSUE THREAD

**Issue by vadimgn** [solomonkinard/public#18]
Hello,

I have encountered a minor issue when using the Chromium Context extension in vs code. Among the listed features it defined file association for `.gni` files as `gni`, while it should be `gn`. It messes up the syntax highlighting provided by other extensions. I was unable to reliably change the file association to `gn` until I have disabled the Chromium Context extension. It was somehow overriding my file association settings.
![cr_context_ext_issue](https://github.com/user-attachments/assets/c3c8757b-7320-4669-af55-c70dccb59944)

**Comment by solomonkinard** [comment]
This was just removed as of v0.4.0. Do you want to verify? It was added before then to offer syntax highlighting and at that point, I would have expected chromium-context.config.language.change set to false to have disabled any conflicts. Anyway, this is hopefully a quick fix to your problem without understanding all of the details. Maybe no one will notice that this has changed to meet your needs.
