### ISSUE TITLE
Feature: Put all commands in the command pallete

### ISSUE THREAD

**Issue by hrdwdmrbl** [solomonkinard/public#2]
I think you should put all of these commands in the pallete because keyboard shortcuts rock!

![Screenshot 2023-03-17 at 00 47 20](https://user-images.githubusercontent.com/554881/225815064-1e078bca-0582-4dd8-b27c-c2a725d137a9.png)

(Putting just the "Open commit on the web" in the command pallete would be my #1 feature request)

**Comment by solomonkinard** [comment]
Available in v0.1.820230419. Open Online now available. I'm not sure much much longer previous line and file history are going to last. They seem redundant after adding Git Blame File and Git Blame Line menus. I'm also not sure how useful copy commit information to clipboard actually is. Feel free to share if you have any ideas. Anyway, all of your various bugs have been resolved.
