### ISSUE TITLE
Feature: "Open commit on the web" should open to the exact line

### ISSUE THREAD

**Issue by hrdwdmrbl** [solomonkinard/public#3]
For example, instead of just opening a commit like

https://github.com/solomonkinard/public/commit/f5e111b8f71556b2ace7570af4dcf7951f94987d

it should open

https://github.com/solomonkinard/public/commit/f5e111b8f71556b2ace7570af4dcf7951f94987d#diff-f83c498eb5a956f05658cfb4247bbc0b3b6e01b2bfa3285c988a88245decf0b8R4

(This would be my #2 feature request)

**Comment by solomonkinard** [comment]
in v0.1.5 and 0.1.6, I observed the behavior that you're asking for. You can provide reproduction steps and/or a video if you're experiencing otherwise.
