### ISSUE TITLE
Feature: "Edit web url" should be a VS Code setting

### ISSUE THREAD

**Issue by hrdwdmrbl** [solomonkinard/public#4]
It would be nice to integrate this setting into the other VS Code settings.

For example, here are the settings for the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
![Screenshot 2023-03-17 at 10 39 31](https://user-images.githubusercontent.com/554881/225936288-2e612b5e-c5f8-4ec1-bf33-3141e18b02d3.png)

When I saw the "Open commit on the web" button was defaulting to Google, my first instinct was to try to change a setting. I didn't know to edit the setting through this extensions command options.

**Comment by solomonkinard** [comment]
Done in v0.1.6 (https://marketplace.visualstudio.com/items?itemName=solomonkinard.git-blame).
