### ISSUE TITLE
Navigation does not work on VSCode for Windows

### ISSUE THREAD

**Issue by taenri** [solomonkinard/public#6]
Ctrl+Alt+K successfully toggles bookmark but Ctrl+Alt+J does not navigate to the next one.

**Comment by RayBrack** [comment]
Clicking on the line number also doesn't work.
I notice the previous issue was raised almost 8 months ago.  Are there any plans to correct the issue?

**Comment by solomonkinard** [comment]
Fixed in 0.0.12 after borrowing a physical machine that had the OS that you've all reported.
