### ISSUE TITLE
Git blame inline alongside code is not appearing 

### ISSUE THREAD

**Issue by NEELAKANTAPPA-M** [solomonkinard/public#8]
I have checked 'Git-blame > Config: Show blame Inline' in extension settings . Still blame is not appearing in inline alongside code.

Git-Blame version: 0.2.1
Vs code version: 1.84

**Comment by solomonkinard** [comment]
Is editor line wrapping disabled? What OS? Screenshot?

**Comment by NEELAKANTAPPA-M** [comment]
Hi @solomonkinard,
Thanks for the clue. Word wrapping was disabled.

Now it's looks fine.
