### ISSUE TITLE
Add a shorcuts for list files

### ISSUE THREAD

**Issue by AesthetiCoder** [solomonkinard/public#9]
![image](https://github.com/solomonkinard/public/assets/70770072/0ab3bb87-1efd-44ab-8200-c718fd2d139f)

**Comment by solomonkinard** [comment]
Can you clarify with more context?

**Comment by AesthetiCoder** [comment]
yes sure, it will be nice to show all the files that are in favorites in a list like this and have a shortcut for that

**Comment by solomonkinard** [comment]
Done in v0.0.5. Thanks.
